# Generated by Django 5.2.8 on 2025-12-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0002_pets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pets',
            new_name='Pet',
        ),
    ]
