# Generated by Django 5.2.8 on 2025-12-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0003_rename_pets_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='dono',
            name='data_cadastro',
            field=models.DateField(null=True),
        ),
    ]
